A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://react.dev/link/controlled-components
TypeError: Failed to fetch
    at https://9000-firebase-studio-1746766542183.cluster-f4iwdviaqvc2ct6pgytzw4xqy4.cloudworkstations.dev/_next/static/chunks/node_modules_ab79cd6b._.js:15584:23

    at _handleRequest (https://9000-firebase-studio-1746766542183.cluster-f4iwdviaqvc2ct6pgytzw4xqy4.cloudworkstations.dev/_next/static/chunks/node_modules_ab79cd6b._.js:15878:24)

    at _request (https://9000-firebase-studio-1746766542183.cluster-f4iwdviaqvc2ct6pgytzw4xqy4.cloudworkstations.dev/_next/static/chunks/node_modules_ab79cd6b._.js:15865:24)

    at SupabaseAuthClient.signUp (https://9000-firebase-studio-1746766542183.cluster-f4iwdviaqvc2ct6pgytzw4xqy4.cloudworkstations.dev/_next/static/chunks/node_modules_ab79cd6b._.js:16807:219)

    at onSubmit (https://9000-firebase-studio-1746766542183.cluster-f4iwdviaqvc2ct6pgytzw4xqy4.cloudworkstations.dev/_next/static/chunks/src_49401849._.js:876:188)

    at https://9000-firebase-studio-1746766542183.cluster-f4iwdviaqvc2ct6pgytzw4xqy4.cloudworkstations.dev/_next/static/chunks/node_modules_ab79cd6b._.js:2189:27